name: ip_pomoshnik_kz_flutter
description: MVP Flutter app for entrepreneurs in Kazakhstan.
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

flutter:
  uses-material-design: true
